[".vim/pack/plugins/start/chezmoi.vim"]
    type = "git-repo"
    url = "https://github.com/alker0/chezmoi.vim.git"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/ctrlp.vim.git"]
    type = "git-repo"
    url = "https://github.com/kien/ctrlp.vim.git"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/supertab.git"]
    type = "git-repo"
    url = "https://github.com/ervandew/supertab.git"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/tabular.git"]
    type = "git-repo"
    url = "https://github.com/godlygeek/tabular.git"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/tComment.git"]
    type = "git-repo"
    url = "https://github.com/vim-scripts/tComment.git"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/vala.vim"]
    type = "git-repo"
    url = "https://github.com/vala-lang/vala.vim"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/diffchar.vim"]
    type = "git-repo"
    url = "https://github.com/rickhowe/diffchar.vim"
    refreshPeriod = "168h"
